import { ChatKit, useChatKit } from "@openai/chatkit-react";
import type { Widgets } from "@openai/chatkit";
import { useCallback, useEffect, useMemo, useState } from "react";

const CHATKIT_API_URL = import.meta.env.VITE_API_URL || "http://localhost:8000/chatkit";
const CHATKIT_API_DOMAIN_KEY = import.meta.env.VITE_CHATKIT_API_DOMAIN_KEY ?? "domain_pk_localhost_dev";

type ReferenceSource = {
  key: string;
  title: string;
  subtitle?: string;
  kind: "url" | "file" | "entity" | "unknown";
};

function toPx(value?: number | string) {
  if (value === undefined) return undefined;
  return typeof value === "number" ? `${value}px` : value;
}

function resolveThemeColor(
  color: string | { light: string; dark: string } | undefined,
  scheme: "light" | "dark"
) {
  if (!color) return undefined;
  if (typeof color === "string") return color;
  return scheme === "dark" ? color.dark : color.light;
}

// TODO: NOTE: This was generated by Codex, and seems sub-optimal, but good enough for demo
function WidgetRenderer({
  node,
  colorScheme,
}: {
  node: Widgets.WidgetRoot | Widgets.WidgetComponent;
  colorScheme: "light" | "dark";
}) {
  switch (node.type) {
    case "Basic": {
      return (
        <div
          className="flex"
          style={{
            flexDirection: node.direction === "row" ? "row" : "column",
            gap: toPx(node.gap),
            padding: toPx(node.padding),
            alignItems: node.align,
            justifyContent: node.justify,
          }}
        >
          {node.children?.map((child, index) => (
            <WidgetRenderer key={child.id ?? child.key ?? index} node={child} colorScheme={colorScheme} />
          ))}
        </div>
      );
    }
    case "Card": {
      return (
        <div
          className="rounded-xl border border-gray-200 bg-white shadow-sm"
          style={{
            padding: toPx(node.padding),
            background: resolveThemeColor(node.background, colorScheme),
          }}
        >
          {node.children?.map((child, index) => (
            <WidgetRenderer key={child.id ?? child.key ?? index} node={child} colorScheme={colorScheme} />
          ))}
        </div>
      );
    }
    case "ListView": {
      return (
        <div
          className={[
            "flex flex-col divide-y",
            colorScheme === "dark" ? "divide-slate-700" : "divide-gray-200",
          ].join(" ")}
        >
          {node.children?.map((child, index) => (
            <WidgetRenderer key={child.id ?? child.key ?? index} node={child} colorScheme={colorScheme} />
          ))}
        </div>
      );
    }
    case "ListViewItem": {
      return (
        <div className="flex flex-col gap-1 py-2">
          {node.children?.map((child, index) => (
            <WidgetRenderer key={child.id ?? child.key ?? index} node={child} colorScheme={colorScheme} />
          ))}
        </div>
      );
    }
    case "Box":
    case "Row":
    case "Col": {
      return (
        <div
          className="flex"
          style={{
            flexDirection: node.type === "Row" ? "row" : "column",
            gap: toPx(node.gap),
            padding: toPx(node.padding),
            alignItems: node.align,
            justifyContent: node.justify,
            background: resolveThemeColor(node.background, colorScheme),
          }}
        >
          {node.children?.map((child, index) => (
            <WidgetRenderer key={child.id ?? child.key ?? index} node={child} colorScheme={colorScheme} />
          ))}
        </div>
      );
    }
    case "Divider": {
      return (
        <div
          className={[
            "h-px w-full",
            colorScheme === "dark" ? "bg-slate-700" : "bg-gray-200",
          ].join(" ")}
        />
      );
    }
    case "Title": {
      return <div className={`text-lg text-center font-semibold ${colorScheme === "dark" ? "text-gray-200" : "text-gray-900"}`}>{node.value}</div>;
    }
    case "Text": {
      return <div className={`text-md ${colorScheme === "dark" ? "text-gray-200" : "text-gray-700"}`}>{node.value}</div>;
    }
    case "Caption": {
      return <div className={`text-sm ${colorScheme === "dark" ? "text-gray-400" : "text-gray-500"}`}>{node.value}</div>;
    }
    case "Spacer": {
      return <div style={{ height: toPx(node.minSize) }} />;
    }
    default:
      return null;
  }
}

function ReferencesWidgetPanel({
  colorScheme,
  referencesWidget,
}: {
  colorScheme: "light" | "dark";
  referencesWidget: Widgets.BasicRoot;
}) {
  const panelClasses = [
    "h-[600px] w-[360px] rounded-3xl border shadow-lg overflow-hidden",
    colorScheme === "dark" ? "border-slate-700 bg-black" : "border-gray-200 bg-white",
  ].join(" ");

  return (
    <div className={panelClasses}>
      <div className="h-full w-full overflow-y-auto p-3">
        <WidgetRenderer node={referencesWidget} colorScheme={colorScheme} />
      </div>
    </div>
  );
}

type SettingsPanelProps = {
  colorScheme: "light" | "dark";
  radius: "pill" | "round" | "soft" | "sharp";
  density: "compact" | "normal" | "spacious";
  onColorSchemeChange: (value: "light" | "dark") => void;
  onRadiusChange: (value: "pill" | "round" | "soft" | "sharp") => void;
  onDensityChange: (value: "compact" | "normal" | "spacious") => void;
};

function SettingsPanel({
  colorScheme,
  radius,
  density,
  onColorSchemeChange,
  onRadiusChange,
  onDensityChange,
}: SettingsPanelProps) {
  return (
    <div className="mb-3 flex flex-wrap gap-4 font-sans text-md">
      <label className="flex flex-col gap-1">
        <span className="text-gray-700">Color scheme</span>
        <select
          className="rounded border border-gray-300 bg-white px-2 py-1"
          value={colorScheme}
          onChange={(e) => onColorSchemeChange(e.target.value as "light" | "dark")}
        >
          <option value="light">light</option>
          <option value="dark">dark</option>
        </select>
      </label>
      <label className="flex flex-col gap-1">
        <span className="text-gray-700">Radius</span>
        <select
          className="rounded border border-gray-300 bg-white px-2 py-1"
          value={radius}
          onChange={(e) => onRadiusChange(e.target.value as "pill" | "round" | "soft" | "sharp")}
        >
          <option value="pill">pill</option>
          <option value="round">round</option>
          <option value="soft">soft</option>
          <option value="sharp">sharp</option>
        </select>
      </label>
      <label className="flex flex-col gap-1">
        <span className="text-gray-700">Density</span>
        <select
          className="rounded border border-gray-300 bg-white px-2 py-1"
          value={density}
          onChange={(e) => onDensityChange(e.target.value as "compact" | "normal" | "spacious")}
        >
          <option value="compact">compact</option>
          <option value="normal">normal</option>
          <option value="spacious">spacious</option>
        </select>
      </label>
    </div>
  );
}

export default function App() {
  const [isMounted, setIsMounted] = useState(false);
  const [colorScheme, setColorScheme] = useState<"light" | "dark">("light");
  const [radius, setRadius] = useState<"pill" | "round" | "soft" | "sharp">("round");
  const [density, setDensity] = useState<"compact" | "normal" | "spacious">("normal");
  const [activeThreadId, setActiveThreadId] = useState<string | null>(null);
  const [referenceSources, setReferenceSources] = useState<ReferenceSource[]>([]);
  const [isLoadingReferences, setIsLoadingReferences] = useState(false);

  const fetchLatestReferences = useCallback(async () => {
    if (!activeThreadId) {
      setReferenceSources([]);
      return;
    }
    setIsLoadingReferences(true);
    try {
      const response = await fetch(CHATKIT_API_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: "items.list",
          params: {
            thread_id: activeThreadId,
            limit: 50,
            order: "desc",
          },
        }),
      });

      const payload = await response.json();
      const items = Array.isArray(payload?.data) ? payload.data : [];
      const latestAssistant = items.find(
        (item: any) =>
          item?.type === "assistant_message" &&
          Array.isArray(item?.content) &&
          item.content.some((part: any) => Array.isArray(part?.annotations) && part.annotations.length > 0)
      );

      if (!latestAssistant) {
        setReferenceSources([]);
        return;
      }

      const rawSources = (latestAssistant.content ?? [])
        .flatMap((part: any) => part?.annotations ?? [])
        .map((annotation: any) => annotation?.source)
        .filter(Boolean);

      const unique = new Map<string, ReferenceSource>();
      for (const source of rawSources) {
        const kind = source?.type ?? "unknown";
        const title = source?.title ?? "Untitled reference";
        const subtitle =
          kind === "url"
            ? source?.url
            : kind === "file"
              ? source?.filename ?? source?.description
              : kind === "entity"
                ? source?.label ?? source?.id
                : source?.description;
        const key = `${kind}|${title}|${subtitle ?? ""}`;
        if (!unique.has(key)) {
          unique.set(key, { key, title, subtitle, kind });
        }
      }

      setReferenceSources(Array.from(unique.values()));
    } catch (error) {
      console.error("Failed to load references", error);
      setReferenceSources([]);
    } finally {
      setIsLoadingReferences(false);
    }
  }, [activeThreadId]);
  const chatkit = useChatKit({
    api: {
      url: CHATKIT_API_URL,
      domainKey: CHATKIT_API_DOMAIN_KEY,
    },
    initialThread: activeThreadId,
    theme: {
      colorScheme, // Alternatives: "light", "dark"
      radius,   // Alternatives: "pill", "round", "soft", "sharp"
      density // Alternatives: "compact", "normal", "spacious"
    },
    onThreadChange: (e) => setActiveThreadId(e.threadId),
    onResponseEnd: () => {
      void fetchLatestReferences();
    },
    onReady: () => console.log("ChatKit ready"),
    onError: (e) => console.error("ChatKit error:", e.error),
    onLog: (e) => console.log("ChatKit log:", e.name, e.data),
    onEffect: (e) => console.log("ChatKit effect:", e.name, e.data),
    startScreen: {
      greeting: "Hello! I'm your ChatKit assistant. Ask me anything broski!",
      prompts: [
      {
        icon: 'circle-question',
        label: 'What is Yext Search?',
        prompt: 'What is Yext Search?'
      },
      {
        icon: 'circle-question',
        label: 'Help me with a Search Frontend',
        prompt: 'How can I set up a new Search Frontend?'
      },
      {
        icon: 'circle-question',
        label: 'What are custom phrases?',
        prompt: 'What are custom phrases in Yext Search?'
      },
    ],
    // prompts: [
    //   {
    //     icon: 'circle-question',
    //     label: 'How can I contact support?',
    //     prompt: 'How can I contact support?'
    //   },
    //   {
    //     icon: 'circle-question',
    //     label: 'Good phones for gaming',
    //     prompt: 'What are good phones for gaming?'
    //   },
    //   {
    //     icon: 'circle-question',
    //     label: 'What is airplane mode?',
    //     prompt: 'What is airplane mode?'
    //   },
    // ],
    },
    composer: {
      placeholder: "Type your message...",
    },
  });

  useEffect(() => {
    setIsMounted(true);
  }, [chatkit]);

  useEffect(() => {
    void fetchLatestReferences();
  }, [fetchLatestReferences]);

  const referencesWidget = useMemo<Widgets.BasicRoot>(() => {
    const children: Widgets.WidgetComponent[] = [
      { type: "Title", value: "References" },
      {
        type: "Caption",
        value: activeThreadId ? "From the latest assistant response" : "No thread selected yet",
      },
      { type: "Divider" },
    ];

    if (isLoadingReferences) {
      children.push({ type: "Text", value: "Loading references..." });
    } else if (referenceSources.length === 0) {
      children.push({ type: "Text", value: "No references found in the latest response." });
    } else {
      referenceSources.forEach((source) => {
        children.push({
          type: "Box",
          direction: "col",
          gap: 4,
          padding: 8,
          background: { light: "#f8fafc", dark: "#0b1220" },
          children: [
            { type: "Text", value: source.title, weight: "semibold", size: "xl" },
            {
              type: "Caption",
              value: source.subtitle ?? source.kind.toUpperCase(),
            },
          ],
        });
      });
    }

    return {
      type: "Basic",
      direction: "col",
      gap: 8,
      padding: 12,
      children,
    };
  }, [activeThreadId, isLoadingReferences, referenceSources]);

  if (!isMounted) {
    return (
      <div className="flex items-center justify-center h-screen font-sans">
        Loading ChatKit...
      </div>
    );
  }

  return (
    <div className="flex flex-col w-screen h-screen p-5 bg-gray-50 box-border">
      <div className="bg-gray-100 p-4 mb-5 rounded-lg font-mono text-sm border border-gray-300">
        <div className="font-bold mb-2">ChatKit Debug Info:</div>
        <div>API URL: <code className="bg-gray-200 px-1 rounded">{CHATKIT_API_URL}</code></div>
        <div>Domain Key: <code className="bg-gray-200 px-1 rounded">{CHATKIT_API_DOMAIN_KEY}</code></div>
        <div>Status: {chatkit ? '✅ Initialized' : '❌ Not Initialized'}</div>
        {chatkit?.control && <div>Control Methods: {Object.keys(chatkit.control).join(', ')}</div>}
      </div>
      
      <div className="flex-1 flex flex-col border-2 border-blue-500 rounded-lg overflow-hidden min-h-[500px] relative bg-white">
        <SettingsPanel
          colorScheme={colorScheme}
          radius={radius}
          density={density}
          onColorSchemeChange={setColorScheme}
          onRadiusChange={setRadius}
          onDensityChange={setDensity}
        />
        {chatkit?.control ? (
          <div className="flex flex-1 items-center justify-center gap-6 px-6 pb-6">
            {chatkit.control && (
              <>
                <ChatKit 
                  control={chatkit.control}
                  className="h-[600px] w-[360px] shadow-xl rounded-3xl border-2 overflow-hidden"
                  key={`${colorScheme}-${radius}-${density}`} // Force re-render on theme change
                />
                <ReferencesWidgetPanel
                  colorScheme={colorScheme}
                  referencesWidget={referencesWidget}
                />
                <div className="absolute bottom-2.5 right-2.5 bg-black/70 text-white px-2 py-1 rounded text-xs z-[1000]">
                  ChatKit Container
                </div>
              </>
            )}
          </div>
        ) : (
          <div className="flex items-center justify-center h-full text-gray-600 font-sans">
            Initializing ChatKit...
          </div>
        )}
      </div>
    </div>
  );
}
